http:
  routers:
    ocforumfrontend:
      entryPoints:
      - web
      rule: Host(`frontend-forum.localhost`)
      service: ocforumfrontend
  services:
    ocforumfrontend:
      loadBalancer:
        servers:
        - url: http://oc-forum-frontend:5173
